name : deploy and test

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
         node-version: 16
      - name: setup ci
        run: npm ci
      - name: test
        run: npm test

